LogFile = "auth.log"
Regexp = [
'''
(?m)^[a-zA-Z]{3}\s{1,2}\d{1,2}\s+(?P<TIME>(?:\d{2}\:){2}\d{2}).*\:\s+[iI](?:llegal|nvalid) user .* from (?P<HOST>(?:\d{1,3}\.){3}\d{1,3})$
''',
]
MaxFail = 3
BanTime = 1
ActionBan = '''
echo Banning IP <IP>
'''
ActionUnBan = '''
echo Unbanning IP <IP>
'''
Enabled = true
