LogFile = "auth.log"
TimeFormat = "Jan _2 15:04:05"
Regexp = [
'''
(?m)^(?P<DATETIME>(?:[a-zA-Z]{3}\s{1,2}\d{1,2}\s+(\d{2}\:){2}\d{2})).*\:\s+[iI](?:llegal|nvalid) user .* from (?P<HOST>(?:\d{1,3}\.){3}\d{1,3})$
''',
]
MaxFail = 3
BanTime = 1
FindTime = 10
ActionBan = '''
echo Banning IP <HOST>
'''
ActionUnBan = '''
echo Unbanning IP <HOST>
'''
ActionSetup = '''
echo Setting up stuff.
'''
Enabled = true
